"""memory reads and knowledge sources

Revision ID: 333f14903f9a
Revises: 29f8662da2d5
Create Date: 2026-08-06 01:20:30.428778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '333f14903f9a'
down_revision: Union[str, Sequence[str], None] = '29f8662da2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('origin', sa.String(length=512), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('content_chars', sa.Integer(), nullable=False),
    sa.Column('memory_paths', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_created_at'), 'knowledge_sources', ['created_at'], unique=False)
    op.create_table('memory_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_reads_created_at'), 'memory_reads', ['created_at'], unique=False)
    op.create_index(op.f('ix_memory_reads_path'), 'memory_reads', ['path'], unique=False)
    op.create_index('ix_memory_reads_path_created', 'memory_reads', ['path', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_reads_path_created', table_name='memory_reads')
    op.drop_index(op.f('ix_memory_reads_path'), table_name='memory_reads')
    op.drop_index(op.f('ix_memory_reads_created_at'), table_name='memory_reads')
    op.drop_table('memory_reads')
    op.drop_index(op.f('ix_knowledge_sources_created_at'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    # ### end Alembic commands ###
