"""drop knowledge_sources

Revision ID: 70b5a4b50eb5
Revises: 333f14903f9a
Create Date: 2026-08-06 01:30:16.403941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70b5a4b50eb5'
down_revision: Union[str, Sequence[str], None] = '333f14903f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_sources_created_at'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_sources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('origin', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content_chars', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('memory_paths', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_sources_pkey'))
    )
    op.create_index(op.f('ix_knowledge_sources_created_at'), 'knowledge_sources', ['created_at'], unique=False)
    # ### end Alembic commands ###
