"""app settings

Revision ID: 9ab96f778b9c
Revises: a1464bcc1e94
Create Date: 2026-08-06 07:48:34.379161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ab96f778b9c'
down_revision: Union[str, Sequence[str], None] = 'a1464bcc1e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_index(op.f('ix_memories_content_trgm'), table_name='memories', postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_messages_search_trgm'), table_name='messages', postgresql_ops={'search_text': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_messages_search_trgm'), 'messages', ['search_text'], unique=False, postgresql_ops={'search_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_memories_content_trgm'), 'memories', ['content'], unique=False, postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
