"""restore trigram search indexes

Revision ID: c6a8f1e2d4b7
Revises: b3d81f0c67a4
Create Date: 2026-08-12 01:45:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6a8f1e2d4b7"
down_revision: str | Sequence[str] | None = "b3d81f0c67a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Restore indexes accidentally removed by the app-settings migration."""
    # 9ab96f778b9c was autogenerated after these hand-written indexes existed.
    # Alembic did not see them in SQLAlchemy metadata and emitted drop_index.
    # IF NOT EXISTS also makes this safe for deployments that restored them by hand.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_messages_search_trgm ON messages "
        "USING gin (search_text gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_memories_content_trgm ON memories "
        "USING gin (content gin_trgm_ops)"
    )


def downgrade() -> None:
    """Remove the indexes restored by this revision."""
    op.execute("DROP INDEX IF EXISTS ix_memories_content_trgm")
    op.execute("DROP INDEX IF EXISTS ix_messages_search_trgm")
